package com.example.board.service;

import com.example.board.entity.PzGridTemplate;
import com.example.board.entity.PzLevel;
import com.example.board.repository.PzGridTemplateRepository;
import com.example.board.repository.PzLevelRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * 그리드 템플릿 관리 서비스
 * 
 * @author Crossword Team
 * @version 1.0.0
 * @since 2025-09-23
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class GridTemplateService {

    private final PzGridTemplateRepository pzGridTemplateRepository;
    private final PzLevelRepository pzLevelRepository;

    /**
     * 모든 템플릿 조회 (페이징 및 검색 조건 포함)
     */
    public Page<PzGridTemplate> getAllTemplates(int page, int size, String sortField, String sortDir,
                                                Integer levelId, String templateName, Integer minWordCount, 
                                                Integer maxWordCount, Integer minIntersectionCount,
                                                Integer maxIntersectionCount) {
        log.info("=== 템플릿 검색 요청 ===");
        log.info("페이지: {}, 크기: {}, 정렬필드: {}, 정렬방향: {}", page, size, sortField, sortDir);
        log.info("검색조건 - 레벨: {}, 템플릿명: {}, 최소단어수: {}, 최대단어수: {}, 최소교차점: {}, 최대교차점: {}", 
                levelId, templateName, minWordCount, maxWordCount, minIntersectionCount, maxIntersectionCount);
        
        Sort sort = Sort.by(sortField);
        sort = sortDir.equalsIgnoreCase("asc") ? sort.ascending() : sort.descending();
        Pageable pageable = PageRequest.of(page, size, sort);

        // 검색 조건이 있는 경우 필터링된 조회, 없는 경우 전체 조회
        if (levelId != null || (templateName != null && !templateName.trim().isEmpty()) ||
            minWordCount != null || maxWordCount != null || 
            minIntersectionCount != null || maxIntersectionCount != null) {
            
            return pzGridTemplateRepository.findBySearchCriteria(
                levelId, templateName, minWordCount, maxWordCount, 
                minIntersectionCount, maxIntersectionCount, pageable);
        } else {
            return pzGridTemplateRepository.findByIsActiveTrue(pageable);
        }
    }

    /**
     * 템플릿 통계 정보 조회
     */
    public Map<String, Object> getTemplateStats() {
        Map<String, Object> stats = new HashMap<>();
        
        try {
            // 기본 통계
            stats.put("totalTemplates", pzGridTemplateRepository.countActiveTemplates());
            stats.put("averageWordCount", pzGridTemplateRepository.findAverageWordCount());
            stats.put("maxWordCount", pzGridTemplateRepository.findMaxWordCount());
            stats.put("minWordCount", pzGridTemplateRepository.findMinWordCount());
            stats.put("averageIntersectionCount", pzGridTemplateRepository.findAverageIntersectionCount());
            stats.put("maxIntersectionCount", pzGridTemplateRepository.findMaxIntersectionCount());
            stats.put("minIntersectionCount", pzGridTemplateRepository.findMinIntersectionCount());
            
            // 레벨별 통계
            List<Object[]> levelStats = pzGridTemplateRepository.countTemplatesByLevel();
            Map<Integer, Long> templatesByLevel = new HashMap<>();
            for (Object[] stat : levelStats) {
                templatesByLevel.put((Integer) stat[0], (Long) stat[1]);
            }
            stats.put("templatesByLevel", templatesByLevel);
            
            log.info("템플릿 통계 조회 완료: {}", stats);
            
        } catch (Exception e) {
            log.error("템플릿 통계 조회 중 오류 발생", e);
            stats.put("error", "통계 조회 중 오류가 발생했습니다: " + e.getMessage());
        }
        
        return stats;
    }

    /**
     * 단일 템플릿 조회
     */
    public Optional<PzGridTemplate> getTemplateById(Long id) {
        return pzGridTemplateRepository.findById(id);
    }

    /**
     * 템플릿 생성
     */
    @Transactional
    public PzGridTemplate createTemplate(PzGridTemplate template) {
        // 템플릿 이름 자동 생성 (라라벨과 동일)
        String autoGeneratedName = generateTemplateName(template.getLevelId());
        template.setTemplateName(autoGeneratedName);
        
        template.setCreatedAt(LocalDateTime.now());
        template.setUpdatedAt(LocalDateTime.now());
        template.setIsActive(true);
        return pzGridTemplateRepository.save(template);
    }
    
    /**
     * 템플릿 이름 자동 생성 (라라벨과 동일한 로직)
     */
    private String generateTemplateName(Integer levelId) {
        try {
            // 레벨 정보 조회
            PzLevel level = pzLevelRepository.findById(levelId.longValue()).orElse(null);
            if (level == null) {
                return "레벨 " + levelId + " 템플릿 #1";
            }
            
            // 같은 레벨 내에서 "레벨 n 템플릿 #숫자" 패턴의 템플릿들 조회
            List<PzGridTemplate> existingTemplates = pzGridTemplateRepository.findByLevelIdOrderByCreatedAtDesc(levelId);
            
            int maxNumber = 0;
            for (PzGridTemplate template : existingTemplates) {
                String templateName = template.getTemplateName();
                // "레벨 n 템플릿 #숫자" 패턴에서 숫자 추출
                java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("레벨 \\d+ 템플릿 #(\\d+)");
                java.util.regex.Matcher matcher = pattern.matcher(templateName);
                
                if (matcher.find()) {
                    int number = Integer.parseInt(matcher.group(1));
                    if (number > maxNumber) {
                        maxNumber = number;
                    }
                }
            }
            
            return "레벨 " + level.getLevel() + " 템플릿 #" + (maxNumber + 1);
        } catch (Exception e) {
            log.error("템플릿 이름 생성 중 오류 발생", e);
            return "레벨 " + levelId + " 템플릿 #1";
        }
    }

    /**
     * 템플릿 저장
     */
    @Transactional
    public PzGridTemplate saveTemplate(PzGridTemplate template) {
        if (template.getCreatedAt() == null) {
            template.setCreatedAt(LocalDateTime.now());
        }
        template.setUpdatedAt(LocalDateTime.now());
        return pzGridTemplateRepository.save(template);
    }

    /**
     * 템플릿 삭제
     */
    @Transactional
    public boolean deleteTemplate(Long id) {
        try {
            if (pzGridTemplateRepository.existsById(id)) {
                pzGridTemplateRepository.deleteById(id);
                log.info("템플릿 삭제 완료: id={}", id);
                return true;
            } else {
                log.warn("삭제할 템플릿을 찾을 수 없습니다: id={}", id);
                return false;
            }
        } catch (Exception e) {
            log.error("템플릿 삭제 중 오류 발생: id={}", id, e);
            return false;
        }
    }

    /**
     * 템플릿 활성화/비활성화
     */
    @Transactional
    public boolean toggleTemplateStatus(Long id) {
        try {
            Optional<PzGridTemplate> templateOpt = pzGridTemplateRepository.findById(id);
            if (templateOpt.isPresent()) {
                PzGridTemplate template = templateOpt.get();
                template.setIsActive(!template.getIsActive());
                template.setUpdatedAt(LocalDateTime.now());
                pzGridTemplateRepository.save(template);
                log.info("템플릿 상태 변경 완료: id={}, isActive={}", id, template.getIsActive());
                return true;
            } else {
                log.warn("상태를 변경할 템플릿을 찾을 수 없습니다: id={}", id);
                return false;
            }
        } catch (Exception e) {
            log.error("템플릿 상태 변경 중 오류 발생: id={}", id, e);
            return false;
        }
    }

    /**
     * 레벨별 템플릿 조회
     */
    public List<PzGridTemplate> getTemplatesByLevel(Integer levelId) {
        return pzGridTemplateRepository.findByLevelIdAndIsActiveTrueOrderByCreatedAtDesc(levelId);
    }

    /**
     * 모든 활성화된 템플릿 조회
     */
    public List<PzGridTemplate> getAllActiveTemplates() {
        return pzGridTemplateRepository.findByIsActiveTrueOrderByLevelIdAscCreatedAtDesc();
    }
}